version: '3.9'

services:
  db:
    image: mariadb:10.2
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - app-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=miningstats_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app-network
    ports:
      - 23306:3306
  miningstats-backend:
    container_name: 'miningstats-backend'
    build: .
    depends_on:
      - db
    networks:
      - app-network
    # volumes:
    #   - .:/miningstats-backend
    #   - node_modules:/miningstats-backend/node_modules
    ports:
      - 7314:7314
    # stdin_open: true
    environment:
      - PORT=7314
    command: npm start
networks:
  app-network:
volumes:
  # node_modules:
  app-volume:
